#include <cutil/std/inttypes.h>

#include <cutil/util/compare.h>

extern inline int
cutil_compare_bytes(const void *lhs, const void *rhs, size_t num);

extern inline int
cutil_compare_sizes(
  const void *lhs, const void *rhs, size_t size_lhs, size_t size_rhs
);

#define CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(TYPE, ID)                   \
    extern inline int cutil_compare_##ID(const void *lhs, const void *rhs);

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(char, char)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(short int, short)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(int, int)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(long int, long)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(long long int, llong)

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(unsigned char, uchar)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(unsigned short int, ushort)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(unsigned int, uint)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(unsigned long int, ulong)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(unsigned long long int, ullong)

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(int8_t, i8)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(int16_t, i16)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(int32_t, i32)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(int64_t, i64)

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(uint8_t, u8)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(uint16_t, u16)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(uint32_t, u32)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(uint64_t, u64)

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(size_t, size_t)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(cutil_hash_t, hash_t)

CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(float, float)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(double, double)
CUTIL_TEMPLATE_DECLARE_COMPARISON_FUNCTION(long double, ldouble)
